name: behabior
description: Professional 2D pixel defender game built with Flutter & Flame Engine.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0
  flame_forge2d: ^0.17.0
  flame_audio: ^2.1.0
  flame_rive: ^1.11.0
  rive: ^0.14.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/images/sprites/
    - assets/images/backgrounds/
    - assets/images/ui/
    - assets/images/naves/
    - assets/fonts/
